language: cpp
cache: apt
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install build-essential libtool autotools-dev autoconf libssl-dev pkg-config ccache
  - sudo apt-get install libboost1.55-dev libboost-chrono1.55-dev libboost-filesystem1.55-dev libboost-program-options1.55-dev libboost-system1.55-dev libboost-test1.55-dev libboost-thread1.55-dev
  - sudo apt-get install libdb++-dev
  - sudo apt-get install libqt4-dev 
  - sudo apt-get install  libprotobuf-dev protobuf-compiler
  - export CCACHE_DIR=$HOME/.ccache
  - ccache -M 1G
script:
  - ./autogen.sh 
  - CFLAGS="-O1" CXXFLAGS="-O1" ./configure --with-incompatible-bdb
  - make -j 2
  - make check
  - make clean
  - CFLAGS="-O1" CXXFLAGS="-O1" ./configure --disable-wallet
  - make -j 2
  - make check
notifications:
  irc:
    channels:
      - "chat.freenode.net#indocoin-dev"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
